"""Import a resume file into a CandidateProfile (config/candidate.yaml).

Turns hand-authoring YAML into "point it at your resume". Reads .txt/.md
(stdlib), .pdf (pypdf), .docx (python-docx), then structures it two ways:

- profile_from_text_llm: Bedrock structures name/headline/skills/bullets. It's
  importing the candidate's OWN resume, so bullets are copied faithfully — the
  prompt forbids inventing achievements (CON-4 still holds downstream).
- profile_from_text_heuristic: offline fallback — taxonomy skill scan + bullet
  lines. Cruder, but needs no network.

The result is a dict shaped for CandidateProfile.from_dict.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from src.match.taxonomy import normalize_skills, recognizable_tokens

_BULLET_LEAD = ("-", "•", "*", "–", "—", "·", "▪")


def read_resume_text(path: str | Path) -> str:
    """Extract plain text from a resume file."""
    p = Path(path)
    ext = p.suffix.lower()
    if ext in (".txt", ".md", ""):
        return p.read_text(encoding="utf-8", errors="ignore")
    if ext == ".pdf":
        try:
            from pypdf import PdfReader
        except ImportError as exc:
            raise RuntimeError("PDF import needs pypdf — `pip install pypdf`") from exc
        reader = PdfReader(str(p))
        return "\n".join((page.extract_text() or "") for page in reader.pages)
    if ext == ".docx":
        try:
            import docx
        except ImportError as exc:
            raise RuntimeError("DOCX import needs python-docx — `pip install python-docx`") from exc
        return "\n".join(par.text for par in docx.Document(str(p)).paragraphs)
    raise RuntimeError(f"unsupported resume format '{ext}' (use .txt/.md/.pdf/.docx)")


def _scan_skills(text: str) -> list[str]:
    """Canonical skills present in the text (taxonomy word-boundary scan)."""
    low = text.lower()
    found: list[str] = []
    for tok in recognizable_tokens():
        if re.search(r"\b" + re.escape(tok) + r"\b", low):
            found.append(tok)
    return normalize_skills(found)


def profile_from_text_heuristic(text: str) -> dict[str, Any]:
    lines = text.splitlines()
    nonempty = [l.strip() for l in lines if l.strip()]
    name = nonempty[0] if nonempty else ""
    headline = nonempty[1] if len(nonempty) > 1 else ""

    bullets: list[dict[str, Any]] = []
    seen: set[str] = set()
    for line in lines:
        stripped = line.strip()
        body = stripped.lstrip("".join(_BULLET_LEAD) + " \t").strip()
        is_bullet = stripped.startswith(_BULLET_LEAD) or (30 <= len(body) <= 400)
        if not is_bullet or not (15 <= len(body) <= 400) or body in seen:
            continue
        seen.add(body)
        bullets.append({"text": body, "skills": _scan_skills(body)})
        if len(bullets) >= 25:
            break

    return {
        "name": name, "headline": headline,
        "skills": _scan_skills(text), "master_bullets": bullets,
    }


_LLM_SYSTEM = (
    "You convert a resume into a structured profile. Return ONLY JSON: "
    '{"name": "", "headline": "", "skills": [], '
    '"master_bullets": [{"text": "", "skills": []}]}. '
    "Copy each bullet's text faithfully from the resume (you may fix formatting "
    "but NEVER invent achievements, employers, metrics, or skills the resume "
    "does not contain). skills = concrete technologies the person actually used "
    "(short names). headline = their current role/title."
)


def profile_from_text_llm(text: str, llm: Any) -> dict[str, Any]:
    data = llm.converse_json(_LLM_SYSTEM, text, max_tokens=2000, temperature=0.1)
    return {
        "name": data.get("name", ""),
        "headline": data.get("headline", ""),
        "skills": data.get("skills", []) or [],
        "master_bullets": data.get("master_bullets", []) or [],
    }


def build_profile_dict(raw: dict[str, Any]) -> dict[str, Any]:
    """Normalize skills, assign stable bullet ids, and drop empty bullets."""
    bullets = []
    for i, b in enumerate(raw.get("master_bullets", []), start=1):
        text = (b.get("text") or "").strip()
        if not text:
            continue
        bullets.append({
            "id": f"b{i}",
            "text": text,
            "skills": normalize_skills(b.get("skills", []) or []),
        })
    return {
        "name": raw.get("name", "") or "",
        "headline": raw.get("headline", "") or "",
        "skills": normalize_skills(raw.get("skills", []) or []),
        "master_bullets": bullets,
        "prefs": {"min_comp": None, "remote_only": True},
    }


def to_yaml(profile: dict[str, Any]) -> str:
    import yaml

    header = ("# Generated by `run.py import-resume` from your resume. Review it —\n"
              "# bullets and skills drive tailoring, and only what's here is ever used.\n\n")
    return header + yaml.safe_dump(profile, sort_keys=False, allow_unicode=True)
